Fixed reference to RestSharp.Build.Signed
This was causing build errors as:

Error CS1577: Referenced assembly `RestSharp.Build, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=null' does not have a strong name
(CS1577) (RestSharp.Net35.Signed)

IDE: Xamarin Studio
OS: OS X El Capitan