Change RestResponse to IRestResponse in sample code
Running the example as-is throws `DNX,Version=v4.5.1 error CS0266: Cannot implicitly convert type 'RestSharp.IRestResponse' to 'RestSharp.RestResponse'. An explicit conversion exists (are you missing a cast?)` under .NET Core.

Happy to be told I'm wrong :)